apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 3
  template:
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: general
        its-camera-ai/node-type: general-workload
      containers:
      - name: argocd-repo-server
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: repo-cache
          mountPath: /tmp/cache
      volumes:
      - name: repo-cache
        emptyDir:
          sizeLimit: 10Gi