apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    app.kubernetes.io/managed-by: kubectl
    its-camera-ai.io/component: gitops
    its-camera-ai.io/tier: infrastructure