# Docker Compose for ITS Camera AI
# Supports development, testing, and production environments

version: '3.8'

services:
  # Main Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: its-camera-ai-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
      - "${METRICS_PORT:-8001}:8001"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DATABASE_URL=postgresql+asyncpg://its_user:its_password@postgres:5432/its_camera_ai
      - REDIS_URL=redis://redis:6379/0
      - INFLUXDB_URL=http://influxdb:8086
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_SECURE=false
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}
    volumes:
      - ${PWD}/src:/app/src
      - ${PWD}/data:/app/data
      - ${PWD}/logs:/app/logs
      - ${PWD}/models:/app/models
      - ${PWD}/temp:/app/temp
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - its-network
    profiles:
      - dev
      - prod

  # GPU-enabled Application Service
  app-gpu:
    build:
      context: .
      dockerfile: Dockerfile
      target: gpu-development
    container_name: its-camera-ai-gpu
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
      - "${METRICS_PORT:-8001}:8001"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DATABASE_URL=postgresql+asyncpg://its_user:its_password@postgres:5432/its_camera_ai
      - REDIS_URL=redis://redis:6379/0
      - INFLUXDB_URL=http://influxdb:8086
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_SECURE=false
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
    volumes:
      - ${PWD}/src:/app/src
      - ${PWD}/data:/app/data
      - ${PWD}/logs:/app/logs
      - ${PWD}/models:/app/models
      - ${PWD}/temp:/app/temp
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - its-network
    profiles:
      - gpu

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: its-camera-ai-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: its_camera_ai
      POSTGRES_USER: its_user
      POSTGRES_PASSWORD: its_password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${PWD}/infrastructure/database/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U its_user -d its_camera_ai"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - its-network
    profiles:
      - dev
      - prod
      - gpu

  # Redis Cache and Session Store
  redis:
    image: redis:7-alpine
    container_name: its-camera-ai-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes --requirepass redis_password
    volumes:
      - redis_data:/data
      - ${PWD}/infrastructure/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - its-network
    profiles:
      - dev
      - prod
      - gpu

  # InfluxDB for Time Series Data
  influxdb:
    image: influxdb:2.7-alpine
    container_name: its-camera-ai-influxdb
    restart: unless-stopped
    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin_password
      DOCKER_INFLUXDB_INIT_ORG: its-camera-ai
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin-token-12345
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - its-network
    profiles:
      - dev
      - prod
      - gpu

  # Apache Kafka for Event Streaming
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: its-camera-ai-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zk_data:/var/lib/zookeeper/data
      - zk_logs:/var/lib/zookeeper/log
    networks:
      - its-network
    profiles:
      - dev
      - prod
      - gpu

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: its-camera-ai-kafka
    restart: unless-stopped
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - its-network
    profiles:
      - dev
      - prod
      - gpu

  # MinIO Object Storage (S3-compatible)
  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z
    container_name: its-camera-ai-minio
    restart: unless-stopped
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      # Authentication
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-its_camera_ai_admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-ItsCAI2024SecureMinIOPass!}
      # Performance optimizations
      MINIO_STORAGE_CLASS_STANDARD: EC:2
      MINIO_CACHE_DRIVES: "/mnt/cache1,/mnt/cache2"
      MINIO_CACHE_QUOTA: 80
      MINIO_CACHE_AFTER: 3
      MINIO_CACHE_WATERMARK_LOW: 70
      MINIO_CACHE_WATERMARK_HIGH: 90
      # Security
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_SERVER_URL: http://localhost:9000
      # Logging
      MINIO_AUDIT_WEBHOOK_ENABLE_target1: "on"
      MINIO_AUDIT_WEBHOOK_ENDPOINT_target1: "http://app:8000/api/v1/audit/minio"
    command: >
      sh -c '
        mkdir -p /data/camera-streams /data/ml-models /data/analytics /data/backups &&
        minio server /data --console-address ":9001"
      '
    volumes:
      - minio_data:/data
      - minio_cache1:/mnt/cache1
      - minio_cache2:/mnt/cache2
      - ${PWD}/infrastructure/minio/policies:/opt/minio/policies:ro
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'
    networks:
      - its-network
    profiles:
      - dev
      - prod
      - gpu

  # MinIO Client for bucket initialization
  minio-init:
    image: minio/mc:latest
    container_name: its-camera-ai-minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-its_camera_ai_admin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-ItsCAI2024SecureMinIOPass!}
    entrypoint: >
      sh -c '
        echo "Configuring MinIO..." &&
        mc alias set myminio http://$$MINIO_ENDPOINT $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY &&
        
        echo "Creating buckets..." &&
        mc mb myminio/camera-streams --ignore-existing &&
        mc mb myminio/ml-models --ignore-existing &&
        mc mb myminio/analytics --ignore-existing &&
        mc mb myminio/backups --ignore-existing &&
        mc mb myminio/temp --ignore-existing &&
        
        echo "Setting bucket policies..." &&
        mc policy set download myminio/ml-models &&
        mc policy set private myminio/camera-streams &&
        mc policy set private myminio/analytics &&
        mc policy set private myminio/backups &&
        mc policy set public myminio/temp &&
        
        echo "Configuring lifecycle policies..." &&
        mc ilm add --expiry-days 7 myminio/temp &&
        mc ilm add --expiry-days 30 myminio/camera-streams &&
        mc ilm add --expiry-days 90 myminio/analytics &&
        
        echo "Enabling versioning..." &&
        mc version enable myminio/ml-models &&
        mc version enable myminio/backups &&
        
        echo "MinIO configuration completed successfully!"
      '
    networks:
      - its-network
    profiles:
      - dev
      - prod
      - gpu

  # Prometheus for Metrics Collection
  prometheus:
    image: prom/prometheus:latest
    container_name: its-camera-ai-prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ${PWD}/infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - its-network
    profiles:
      - monitoring

  # Grafana for Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: its-camera-ai-grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ${PWD}/infrastructure/monitoring/grafana:/etc/grafana/provisioning:ro
    networks:
      - its-network
    profiles:
      - monitoring

  # Jupyter Notebook for ML Development
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: its-camera-ai-jupyter
    restart: unless-stopped
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=jupyter-token-12345
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    volumes:
      - ${PWD}:/app
      - jupyter_data:/root/.jupyter
    networks:
      - its-network
    profiles:
      - dev
      - ml

# Named volumes for persistent data
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local
  kafka_data:
    driver: local
  zk_data:
    driver: local
  zk_logs:
    driver: local
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/minio
  minio_cache1:
    driver: local
  minio_cache2:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  jupyter_data:
    driver: local

# Custom network
networks:
  its-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16